// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuarterlySales.Models;

namespace QuarterlySales.Migrations
{
    [DbContext(typeof(SaleRecordContext))]
    partial class SaleRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuarterlySales.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DOB = new DateTime(1972, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Jeremy",
                            HireDate = new DateTime(1996, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lname = "Leights",
                            ManagerID = 1
                        },
                        new
                        {
                            EmployeeID = 2,
                            DOB = new DateTime(1952, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Stanley",
                            HireDate = new DateTime(1996, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Lname = "Medleys",
                            ManagerID = 2
                        });
                });

            modelBuilder.Entity("QuarterlySales.Models.Manager", b =>
                {
                    b.Property<int>("ManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerID");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            ManagerID = 1,
                            FullName = "Clark Stanford"
                        },
                        new
                        {
                            ManagerID = 2,
                            FullName = "Dag Romero"
                        });
                });

            modelBuilder.Entity("QuarterlySales.Models.SaleRecord", b =>
                {
                    b.Property<int>("SaleRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SaleRecordID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("SaleRecords");

                    b.HasData(
                        new
                        {
                            SaleRecordID = 1,
                            Amount = 12000.719999999999,
                            EmployeeID = 1,
                            Quarter = 2,
                            Year = 2001
                        },
                        new
                        {
                            SaleRecordID = 2,
                            Amount = 1883.45,
                            EmployeeID = 2,
                            Quarter = 3,
                            Year = 1997
                        });
                });

            modelBuilder.Entity("QuarterlySales.Models.Employee", b =>
                {
                    b.HasOne("QuarterlySales.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuarterlySales.Models.SaleRecord", b =>
                {
                    b.HasOne("QuarterlySales.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
